#!/usr/bin/env python3
"""Verify data and generate RunPod-specific YOLO and DINO configs."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


SIZES = (200, 400, 600, 800, 1000, 1152)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument(
        "--dino-base-config",
        type=Path,
        help="Optional MMDetection DINO model config to inherit from",
    )
    parser.add_argument(
        "--runtime-root",
        type=Path,
        help="Generated-file destination (default: REPOSITORY/.runtime)",
    )
    parser.add_argument("--skip-hashes", action="store_true")
    return parser.parse_args()


def py_string(value: Path | str) -> str:
    return repr(str(value))


def main() -> None:
    args = parse_args()
    repo = Path(__file__).resolve().parents[1]
    dataset_root = args.dataset_root.resolve()
    verify_command = [
        sys.executable,
        str(repo / "scripts" / "verify_dataset.py"),
        "--dataset-root",
        str(dataset_root),
    ]
    if args.skip_hashes:
        verify_command.append("--skip-hashes")
    subprocess.run(verify_command, check=True)

    runtime = args.runtime_root.resolve() if args.runtime_root else repo / ".runtime"
    split_dir = runtime / "splits"
    yolo_dir = runtime / "yolo"
    dino_dir = runtime / "dino"
    split_dir.mkdir(parents=True, exist_ok=True)
    yolo_dir.mkdir(parents=True, exist_ok=True)
    dino_dir.mkdir(parents=True, exist_ok=True)

    valid_json = (repo / "annotations" / "coco" / "valid.json").resolve()
    test_json = (repo / "annotations" / "coco" / "test.json").resolve()
    summary: dict[str, dict[str, str]] = {}

    for size in SIZES:
        names = (repo / "manifests" / f"train_{size}.txt").read_text(encoding="utf-8").splitlines()
        if len(names) != size or len(set(names)) != size:
            raise ValueError(f"Invalid train_{size} manifest")
        image_paths = [dataset_root / "images" / "train" / name for name in names]
        if any(not path.is_file() for path in image_paths):
            raise FileNotFoundError(f"One or more train_{size} images are missing")

        paths_file = split_dir / f"train_{size}_paths.txt"
        paths_file.write_text("".join(f"{path}\n" for path in image_paths), encoding="utf-8")

        yolo_config = yolo_dir / f"train_{size}.yaml"
        yolo_config.write_text(
            "\n".join(
                (
                    f"path: {dataset_root}",
                    f"train: {paths_file}",
                    "val: images/valid",
                    "test: images/test",
                    "",
                    "nc: 2",
                    "names:",
                    "  0: illustration",
                    "  1: text_block",
                    "",
                )
            ),
            encoding="utf-8",
        )

        dino_config = dino_dir / f"train_{size}.py"
        if args.dino_base_config:
            base_config = args.dino_base_config.resolve()
            if not base_config.is_file():
                raise FileNotFoundError(f"DINO base config not found: {base_config}")
            dino_config.write_text(
                f"""# Generated by scripts/prepare_runtime.py; do not commit this file.
_base_ = {py_string(base_config)}

dataset_type = 'CocoDataset'
data_root = {py_string(str(dataset_root) + '/')}
metainfo = dict(classes=('illustration', 'text_block'))

train_dataloader = dict(dataset=dict(
    type=dataset_type,
    data_root=data_root,
    ann_file={py_string((repo / 'annotations' / 'coco' / f'train_{size}.json').resolve())},
    data_prefix=dict(img='images/train/'),
    metainfo=metainfo,
))
val_dataloader = dict(dataset=dict(
    type=dataset_type,
    data_root=data_root,
    ann_file={py_string(valid_json)},
    data_prefix=dict(img='images/valid/'),
    metainfo=metainfo,
))
test_dataloader = dict(dataset=dict(
    type=dataset_type,
    data_root=data_root,
    ann_file={py_string(test_json)},
    data_prefix=dict(img='images/test/'),
    metainfo=metainfo,
))
val_evaluator = dict(ann_file={py_string(valid_json)})
test_evaluator = dict(ann_file={py_string(test_json)})
""",
                encoding="utf-8",
            )

        summary[str(size)] = {
            "yolo_config": str(yolo_config),
            "dino_config": str(dino_config) if args.dino_base_config else "not generated",
            "train_manifest": str(paths_file),
        }

    (runtime / "runtime_summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Runtime files generated in: {runtime}")
    if not args.dino_base_config:
        print("DINO overlays were not generated; rerun with --dino-base-config /path/to/config.py")


if __name__ == "__main__":
    main()
